//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NERABOTA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabotadatel
    {
        public int id_rabotadatel { get; set; }
        public int id_acc { get; set; }
        public string name_rabot { get; set; }
        public int id_company { get; set; }
        public int id_work { get; set; }
        public string surname_rabot { get; set; }
        public string otchestvo_rabot { get; set; }
        public int id_city { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Work Work { get; set; }
    }
}
