//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NERABOTA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soiskatel
    {
        public int id_sois { get; set; }
        public int id_acc { get; set; }
        public string name_sois { get; set; }
        public int age { get; set; }
        public int id_city { get; set; }
        public string gender { get; set; }
        public string surname_sois { get; set; }
        public string otchestvo_sois { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual City City { get; set; }
    }
}
